#!/bin/bash

set -e

if [ -z "$1" ]
then
      py=python3
else
      py=$1
fi

rm -rf dist
git fetch --all
$py -m build

# we publish to pypi using github action, see .github/workflows/build.yml
# while true; do# 

# read -p "Do you want to publish this package ? (y/n) " yn# 

# case $yn in 
# 	[yY] ) echo publishing to pypi;
# 		break;;
# 	[nN] ) echo exiting;
# 		exit;;
# 	* ) echo invalid response;;
# esac# 

# done# 

# python3 -m twine upload dist/*
